### ISSUE TITLE
Bad Request: 400 Bad Request

### ISSUE THREAD

**Issue by itsbrex** [cameronstanley/mutant#1]
When I run `rake db:migrate` console outputs:

![2016-03-13 at 3 27 pm](https://cloud.githubusercontent.com/assets/9772694/13731814/2e93ba0a-e930-11e5-84f5-9b9a85e11541.jpg)

**Comment by cameronstanley** [comment]
@brianroach, usually that error occurs if the SPOTIFY_CLIENT_ID and/or SPOTIFY_CLIENT_SECRET is not set on the path. Let me know if this doesn't fix it for you. I'll implement a fix to display a friendlier error message in the future.

**Comment by brianroach** [comment]
@cameronstanley when you say "set on the path" you mean the first two steps `export SPOTIFY_CLIENT_SECRET=` and `export SPOTIFY_CLIENT_ID=` correct? If so, then yeah, it's not working for me. Re-set both of those and it failed again at `rake db:migrate`

**Comment by cameronstanley** [comment]
@brianroach, that should be working for you. I'm going to move everything over to use the Figaro gem so it's easier to configure.
